[project]
name = "odoo-addons-oca-e-commerce"
version = "18.0.20241028.0"
dependencies = [
    "odoo-addon-website_sale_checkout_skip_payment==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
